name: call-tf

on: push


jobs:
  tf_init:
    uses: kgopi1/tf_templates/.github/workflows/terraform_action.yaml@main
    secrets: inherit
    with:
      action: init

  tf_plan:
    needs: [tf_init]
    uses: kgopi1/tf_templates/.github/workflows/terraform_action.yaml@main
    secrets: inherit
    with:
      action: plan

  tf_apply:
    needs: [tf_plan]
    uses: kgopi1/tf_templates/.github/workflows/terraform_action.yaml@main
    secrets: inherit
    with:
      action: plan